import {
  FirestoreIcon,
  MongoDBIcon,
  MySQLIcon,
  PostgreSQLIcon,
  RedisIcon,
  SQLLiteIcon,
} from "../icons/db_icons";
import {
  FileCodeIcon,
  JsIcon,
  TsIcon,
  LuaIcon,
  CIcon,
  GoIcon,
  CPPIcon,
  CSharpIcon,
  PyIcon,
  PHPIcon,
  RubyIcon,
  KotlinIcon,
  DartIcon,
  JavaIcon,
  RustIcon,
  SwiftIcon,
  RIcon,
  OcamlIcon,
  PerlIcon,
  NimIcon,
  BashIcon,
  PowershellIcon,
  ZshIcon,
  FishIcon,
  HtmlIcon,
  XmlIcon,
  YamlIcon,
  JsonIcon,
  MarkdownIcon,
  CssIcon,
  SassIcon,
  VIcon,
  GleamIcon,
  JuliaIcon,
  ElixirIcon,
  ErlangIcon,
  CrystalIcon,
  ReasonIcon,
} from "../icons/lang_icons";
import {
  ElectronIcon,
  ReactNativeIcon,
  FlutterIcon,
  VueIcon,
  AngularIcon,
  SvelteIcon,
  EmberIcon,
  NextjsIcon,
  NuxtjsIcon,
  ExpressjsIcon,
  SpringIcon,
  DjangoIcon,
  LaravelIcon,
  RailsIcon,
  FlaskIcon,
  GinIcon,
  PhoenixIcon,
  DotnetIcon,
  JestIcon,
  MochaIcon,
  PyTestIcon,
  PyTorchIcon,
  TailwindIcon,
  BootstrapIcon,
  BulmaIcon,
} from "../icons/Frame_Icons";
import {
  ReactIcon,
  JQueryIcon,
  MongooseIcon,
  ReduxIcon,
  AxiosIcon,
  PrismaIcon,
  PandasIcon,
  ChartjsIcon,
  D3Icon,
  TensorFlowIcon,
  NumPyIcon,
  MdxIcon,
} from "../icons/Lib_Icons";
import { BunIcon, DenoIcon, NodejsIcon } from "../icons/Runtime_icons";
import {
  BabelIcon,
  CargoIcon,
  CurlIcon,
  DockerIcon,
  ESLintIcon,
  GitIcon,
  LuaRocksIcon,
  NeovimIcon,
  NpmIcon,
  ParcelIcon,
  PipIcon,
  PrettierIcon,
  RolldownIcon,
  RollupIcon,
  TmuxIcon,
  VimIcon,
  ViteIcon,
  VscodeIcon,
  WebpackIcon,
  HelixIcon,
  NixIcon,
} from "../icons/DevTools_Icons";
import {
  LinuxIcon,
  MacOSIcon,
  UbuntuIcon,
  WindowsIcon,
} from "../icons/Platform_Icons";
import {
  AsciiIcon,
  BaseConversionIcon,
  BinaryIcon,
  CpuIcon,
  DecimalIcon,
  HexIcon,
  StorageUnitsIcon,
  UnicodeIcon,
} from "../icons/BasicOfCom_Icons";
import { BrowserIcon } from "../icons/Additional_Icons";

const all_cheat_icons = {
  default: <FileCodeIcon />,
  js: <JsIcon />,
  ts: <TsIcon />,
  lua: <LuaIcon />,
  c: <CIcon />,
  cpp: <CPPIcon />,
  cs: <CSharpIcon />,
  go: <GoIcon />,
  py: <PyIcon />,
  php: <PHPIcon />,
  rb: <RubyIcon />,
  kotlin: <KotlinIcon />,
  dart: <DartIcon />,
  java: <JavaIcon />,
  rust: <RustIcon />,
  swift: <SwiftIcon />,
  r: <RIcon />,
  ocaml: <OcamlIcon />,
  perl: <PerlIcon dimension={45} />,
  nim: <NimIcon />,
  v: <VIcon />,
  gleam: <GleamIcon />,
  julia: (
    <span className="text-[#1a1a1a] dark:text-white">
      <JuliaIcon />
    </span>
  ),
  elixir: <ElixirIcon />,
  erlang: <ErlangIcon />,
  crystal: <CrystalIcon />,
  reason: <ReasonIcon />,
  mysql: <MySQLIcon />,
  postgresql: <PostgreSQLIcon />,
  mongodb: <MongoDBIcon />,
  redis: <RedisIcon />,
  firestore: <FirestoreIcon />,
  sqlite: <SQLLiteIcon />,
  nodejs: <NodejsIcon />,
  deno: <DenoIcon />,
  bun: <BunIcon />,
  git: <GitIcon />,
  electron: <ElectronIcon />,
  reactnative: <ReactNativeIcon />,
  flutter: <FlutterIcon />,
  vue: <VueIcon />,
  angular: <AngularIcon />,
  svelte: <SvelteIcon />,
  ember: <EmberIcon />,
  nextjs: <NextjsIcon />,
  nuxtjs: <NuxtjsIcon />,
  expressjs: <ExpressjsIcon />,
  spring: <SpringIcon />,
  django: <DjangoIcon />,
  laravel: <LaravelIcon />,
  rails: <RailsIcon />,
  flask: <FlaskIcon />,
  gin: <GinIcon />,
  phoenix: <PhoenixIcon />,
  dotnet: <DotnetIcon />,
  jest: <JestIcon />,
  mocha: <MochaIcon />,
  pytest: <PyTestIcon />,
  pytorch: <PyTorchIcon />,
  tailwind: <TailwindIcon />,
  bootstrap: <BootstrapIcon />,
  bulma: <BulmaIcon />,
  react: <ReactIcon />,
  jquery: <JQueryIcon />,
  mongoose: <MongooseIcon />,
  redux: <ReduxIcon />,
  axios: <AxiosIcon />,
  prisma: <PrismaIcon />,
  pandas: <PandasIcon />,
  chartjs: <ChartjsIcon />,
  d3: <D3Icon />,
  tensorflow: <TensorFlowIcon />,
  numpy: <NumPyIcon />,
  mdx: <MdxIcon />,
  bash: (
    <span className="dark:text-white">
      <BashIcon />
    </span>
  ),
  powershell: <PowershellIcon />,
  zsh: <ZshIcon />,
  fish: <FishIcon />,
  html: <HtmlIcon />,
  xml: <XmlIcon />,
  yaml: <YamlIcon />,
  json: <JsonIcon />,
  markdown: <MarkdownIcon />,
  css: <CssIcon />,
  sass: <SassIcon />,
  linux: <LinuxIcon />,
  ubuntu: <UbuntuIcon />,
  windows: <WindowsIcon />,
  macos: (
    <span className="dark:text-white">
      <MacOSIcon />
    </span>
  ),
  vscode: <VscodeIcon />,
  vim: <VimIcon />,
  neovim: <NeovimIcon />,
  helix: <HelixIcon />,
  tmux: <TmuxIcon />,
  curl: <CurlIcon />,
  vite: <ViteIcon />,
  webpack: <WebpackIcon />,
  parcel: <ParcelIcon />,
  rollup: <RollupIcon />,
  rolldown: <RolldownIcon />,
  eslint: <ESLintIcon />,
  babel: <BabelIcon />,
  prettier: <PrettierIcon />,
  docker: <DockerIcon />,
  pip: <PipIcon />,
  npm: <NpmIcon />,
  cargo: <CargoIcon />,
  luarocks: <LuaRocksIcon />,
  nix: <NixIcon />,
  binary: <BinaryIcon dimension={30} color="#3791f4" />,
  storage_units: <StorageUnitsIcon dimension={30} color="#8154f0" />,
  hex: (
    <span className="dark:text-white">
      <HexIcon dimension={35} />
    </span>
  ),
  decimal: <DecimalIcon dimension={30} color="#3791f4" />,
  base_conversion: <BaseConversionIcon dimension={28} color="#049500" />,
  _32bit_and_64bit: <CpuIcon dimension={30} color="#ca950b" />,
  ascii: <AsciiIcon dimension={35} color="#0bb7ca" />,
  unicode: <UnicodeIcon dimension={30} color="#ca0b4a" />,
  web_api: (
    <span className="dark:text-white">
      <BrowserIcon />
    </span>
  ),
  nixos: <NixIcon />,
};

export default all_cheat_icons;
