const aliases = {
  "js": "javascript",
  "javascript": "js",
  "python": "py",
  "py": "python",
  "ts": "typescript",
  "typescript": "ts",
  "rs": "rust",
  "rust": "rs",
  "go": "golang",
  "golang": "go",
  "cpp": "c++",
  "c++": "cpp",
  "cs": "c#",
  "c#": "cs",
  "rb": "ruby",
  "ruby": "rb",
  "sh": "shell",
  "shell": "sh",
  "bash": "shell",
  "md": "markdown",
  "markdown": "md",
  "dr": "dart",
  "kt": "kotlin",
  "yml": "yaml",
  "smark": "sommark",
} 

export default aliases;