export default {
    SomMark: {
        compile: async () => "",
        lexer: () => [],
        parser: () => [],
        raw: (html) => ({ __raw: html }),
        static: (expr) => null,
        glob: async () => [],
        getHeadings: async () => [],
        getMetadata: async () => ({}),
    },
    fileHandler: {
        read: async () => "",
        exists: async () => false,
        glob: async () => [],
    },
    pathHandler: {
        join: (...parts) => parts.join("/"),
        resolve: (...parts) => parts.join("/"),
        dirname: (p) => p.split("/").slice(0, -1).join("/"),
        basename: (p) => p.split("/").pop(),
        extname: (p) => { const b = p.split("/").pop(); const i = b.lastIndexOf("."); return i > 0 ? b.slice(i) : ""; },
        normalize: (p) => p,
        relative: (from, to) => to,
        isAbsolute: (p) => p.startsWith("/"),
    },
    glob: (pattern) => [],
    getHeadings: (filePath) => [],
    getMetadata: (filePath) => ({}),
    getData: (folder) => [],
    getPages: () => [],
    getCheatsheets: () => [{
        name: "",
        key: "",
        count: 0,
        iconSvg: "",
        sheets: [{ title: "", url: "", category: "", progress: 0, abbr: "", iconHtml: "", progressDash: "", progressColor: "", barStyle: "", formattedDate: "", aliases: [], tasks: 0, finishedTasks: 0, unfinishedTasks: 0, taskFileLastModified: null, taskList: [] }],
    }],
    getSearchIndex: () => "[]",
    getSearchIndexByCategory: (category) => "[]",
    __currentUrl: "/",
    __currentFile: "",
    __siteUrl: "",
    __isDev: true,
    __params: {},
    __props: {},
    __slug: "",
    __headings: [],
    __cat: {
        name: "",
        key: "",
        count: 0,
        iconSvg: "",
        sheets: [{ title: "", url: "", category: "", progress: 0, abbr: "", iconHtml: "", progressDash: "", progressColor: "", barStyle: "", formattedDate: "", aliases: [], tasks: 0, finishedTasks: 0, unfinishedTasks: 0, taskFileLastModified: null, taskList: [] }],
    },
    __csIconHtml: "",
     __csMeta: {},
     __csCategory: "",
}
