const somcheat_imports = `import Intro from "../../Somcheat-Components/Intro.astro";
import Structure from "../../Somcheat-Components/Structure.astro";
import Section from "../../Somcheat-Components/Section.astro";
import Code from "../../Somcheat-Components/Code.astro";
import Message from "../../Somcheat-Components/Message.astro";
import Link from "../../Somcheat-Components/Link.astro";
import Table from "../../Somcheat-Components/Table.astro";
import Steps from "../../Somcheat-Components/Steps.astro";
import Step from "../../Somcheat-Components/Step.astro";
import Colorize from "../../Somcheat-Components/Colorize.astro";
`;
export default somcheat_imports;